
classdef chess_serviceRequest < ros.Message
    %chess_serviceRequest MATLAB implementation of fishbot_ros/chess_serviceRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'fishbot_ros/chess_serviceRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '60fb4c6aa2ad99bbab7f760122453476' % The MD5 Checksum of the message definition
        PropertyList = { 'PrevMove' } % List of non-constant message properties
        ROSPropertyList = { 'prev_move' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        PrevMove
    end
    methods
        function set.PrevMove(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'chess_serviceRequest', 'PrevMove');
            obj.PrevMove = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.fishbot_ros.chess_serviceRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.fishbot_ros.chess_serviceRequest(strObj);
        end
    end
end
