// Generated by gencpp from file fishbot_ros/chess_serviceResponse.msg
// DO NOT EDIT!


#ifndef FISHBOT_ROS_MESSAGE_CHESS_SERVICERESPONSE_H
#define FISHBOT_ROS_MESSAGE_CHESS_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fishbot_ros
{
template <class ContainerAllocator>
struct chess_serviceResponse_
{
  typedef chess_serviceResponse_<ContainerAllocator> Type;

  chess_serviceResponse_()
    : move()  {
    }
  chess_serviceResponse_(const ContainerAllocator& _alloc)
    : move(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _move_type;
  _move_type move;





  typedef boost::shared_ptr< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct chess_serviceResponse_

typedef ::fishbot_ros::chess_serviceResponse_<std::allocator<void> > chess_serviceResponse;

typedef boost::shared_ptr< ::fishbot_ros::chess_serviceResponse > chess_serviceResponsePtr;
typedef boost::shared_ptr< ::fishbot_ros::chess_serviceResponse const> chess_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fishbot_ros::chess_serviceResponse_<ContainerAllocator1> & lhs, const ::fishbot_ros::chess_serviceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.move == rhs.move;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fishbot_ros::chess_serviceResponse_<ContainerAllocator1> & lhs, const ::fishbot_ros::chess_serviceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fishbot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52369bcdf3840fa4a649505110518725";
  }

  static const char* value(const ::fishbot_ros::chess_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52369bcdf3840fa4ULL;
  static const uint64_t static_value2 = 0xa649505110518725ULL;
};

template<class ContainerAllocator>
struct DataType< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fishbot_ros/chess_serviceResponse";
  }

  static const char* value(const ::fishbot_ros::chess_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string move\n"
;
  }

  static const char* value(const ::fishbot_ros::chess_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.move);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chess_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fishbot_ros::chess_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fishbot_ros::chess_serviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "move: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.move);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FISHBOT_ROS_MESSAGE_CHESS_SERVICERESPONSE_H
