// Generated by gencpp from file fishbot_ros/chess_serviceRequest.msg
// DO NOT EDIT!


#ifndef FISHBOT_ROS_MESSAGE_CHESS_SERVICEREQUEST_H
#define FISHBOT_ROS_MESSAGE_CHESS_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fishbot_ros
{
template <class ContainerAllocator>
struct chess_serviceRequest_
{
  typedef chess_serviceRequest_<ContainerAllocator> Type;

  chess_serviceRequest_()
    : prev_move()  {
    }
  chess_serviceRequest_(const ContainerAllocator& _alloc)
    : prev_move(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _prev_move_type;
  _prev_move_type prev_move;





  typedef boost::shared_ptr< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct chess_serviceRequest_

typedef ::fishbot_ros::chess_serviceRequest_<std::allocator<void> > chess_serviceRequest;

typedef boost::shared_ptr< ::fishbot_ros::chess_serviceRequest > chess_serviceRequestPtr;
typedef boost::shared_ptr< ::fishbot_ros::chess_serviceRequest const> chess_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fishbot_ros::chess_serviceRequest_<ContainerAllocator1> & lhs, const ::fishbot_ros::chess_serviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.prev_move == rhs.prev_move;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fishbot_ros::chess_serviceRequest_<ContainerAllocator1> & lhs, const ::fishbot_ros::chess_serviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fishbot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60fb4c6aa2ad99bbab7f760122453476";
  }

  static const char* value(const ::fishbot_ros::chess_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60fb4c6aa2ad99bbULL;
  static const uint64_t static_value2 = 0xab7f760122453476ULL;
};

template<class ContainerAllocator>
struct DataType< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fishbot_ros/chess_serviceRequest";
  }

  static const char* value(const ::fishbot_ros::chess_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string prev_move\n"
;
  }

  static const char* value(const ::fishbot_ros::chess_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.prev_move);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chess_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fishbot_ros::chess_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fishbot_ros::chess_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "prev_move: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.prev_move);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FISHBOT_ROS_MESSAGE_CHESS_SERVICEREQUEST_H
