// Generated by gencpp from file fishbot_ros/chess_service.msg
// DO NOT EDIT!


#ifndef FISHBOT_ROS_MESSAGE_CHESS_SERVICE_H
#define FISHBOT_ROS_MESSAGE_CHESS_SERVICE_H

#include <ros/service_traits.h>


#include <fishbot_ros/chess_serviceRequest.h>
#include <fishbot_ros/chess_serviceResponse.h>


namespace fishbot_ros
{

struct chess_service
{

typedef chess_serviceRequest Request;
typedef chess_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct chess_service
} // namespace fishbot_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fishbot_ros::chess_service > {
  static const char* value()
  {
    return "c191bbcc538f40c02e38c279fc81b3ad";
  }

  static const char* value(const ::fishbot_ros::chess_service&) { return value(); }
};

template<>
struct DataType< ::fishbot_ros::chess_service > {
  static const char* value()
  {
    return "fishbot_ros/chess_service";
  }

  static const char* value(const ::fishbot_ros::chess_service&) { return value(); }
};


// service_traits::MD5Sum< ::fishbot_ros::chess_serviceRequest> should match
// service_traits::MD5Sum< ::fishbot_ros::chess_service >
template<>
struct MD5Sum< ::fishbot_ros::chess_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fishbot_ros::chess_service >::value();
  }
  static const char* value(const ::fishbot_ros::chess_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fishbot_ros::chess_serviceRequest> should match
// service_traits::DataType< ::fishbot_ros::chess_service >
template<>
struct DataType< ::fishbot_ros::chess_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::fishbot_ros::chess_service >::value();
  }
  static const char* value(const ::fishbot_ros::chess_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fishbot_ros::chess_serviceResponse> should match
// service_traits::MD5Sum< ::fishbot_ros::chess_service >
template<>
struct MD5Sum< ::fishbot_ros::chess_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fishbot_ros::chess_service >::value();
  }
  static const char* value(const ::fishbot_ros::chess_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fishbot_ros::chess_serviceResponse> should match
// service_traits::DataType< ::fishbot_ros::chess_service >
template<>
struct DataType< ::fishbot_ros::chess_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::fishbot_ros::chess_service >::value();
  }
  static const char* value(const ::fishbot_ros::chess_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FISHBOT_ROS_MESSAGE_CHESS_SERVICE_H
